### ISSUE TITLE
Problems using date/time intervals.

### ISSUE THREAD

**Issue by TrevorS** [elixir-lang/ecto#833]
Using latest Elixir, Phoenix, and Ecto (also does not work on version 0.14.2, 0.14.1, or 0.14.0).

Trying to create a function for my model that returns all records inserted in the last `x` minutes:

```elixir
def find_by_inserted_minutes_ago(minutes) do
  from(b in Batch, where: b.inserted_at > datetime_add(^Ecto.DateTime.utc, -1 * ^minutes, "minute"))
end
```

and getting this compilation error back:
```
➜  tsf-pix git:(expiration-on-delete) ✗ mix compile
Compiled lib/tsf_pix.ex
Compiled lib/pix_manager.ex
Compiled lib/user_manager.ex
Compiled lib/pix_manager/pix.ex

== Compilation error on file web/models/batch.ex ==
** (ArgumentError) argument error
    :erlang.apply(0, :type, [])
    lib/ecto/type.ex:230: Ecto.Type.match?/2
    lib/ecto/query/builder.ex:259: Ecto.Query.Builder.assert_type!/3
    lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
    expanding macro: Ecto.Query.where/3
    web/models/batch.ex:17: TsfPix.Batch.find_by_inserted_minutes_ago/1
```

`Ecto.DateTime.utc` works when not using `datetime_add`:
```
iex(6)> Ecto.DateTime.utc
#Ecto.DateTime<2015-07-23T21:58:13Z>

iex(8)> from(b in Batch, where: b.inserted_at > ^Ecto.DateTime.utc) |> Repo.all

15:14:54.536 [debug] SELECT b0."id", b0."user_id", b0."token", b0."file_name", b0."inserted_at", b0."updated_at" FROM "batches" AS b0 WHERE (b0."inserted_at" > $1) [{{2015, 7, 23}, {22, 14, 54, 0}}] OK query=0.7ms
[]
```

Specifying a `%Ecto.DateTime{}` works when not using `datetime_add`:
```
iex(9)> from(b in Batch, where: b.inserted_at > ^%Ecto.DateTime{year: 2015, month: 1, day: 1, hour: 0, min: 0, sec: 0, usec: 0}) |> Repo.all

15:19:04.225 [debug] SELECT b0."id", b0."user_id", b0."token", b0."file_name", b0."inserted_at", b0."updated_at" FROM "batches" AS b0 WHERE (b0."inserted_at" > $1) [{{2015, 1, 1}, {0, 0, 0, 0}}] OK query=8.4ms

...

iex(10)> from(b in Batch, where: b.inserted_at > datetime_add(^%Ecto.DateTime{year: 2015, month: 1, day: 1, hour: 0, min: 0, sec: 0, usec: 0}, -5, "minute")) |> Repo.all
** (ArgumentError) argument error
           :erlang.apply(0, :type, [])
    (ecto) lib/ecto/type.ex:230: Ecto.Type.match?/2
    (ecto) lib/ecto/query/builder.ex:259: Ecto.Query.Builder.assert_type!/3
    (ecto) lib/ecto/query/builder.ex:90: Ecto.Query.Builder.escape/5
    (ecto) lib/ecto/query/builder.ex:142: Ecto.Query.Builder.escape/5
    (ecto) lib/ecto/query/builder/filter.ex:16: Ecto.Query.Builder.Filter.build/5
    (ecto) expanding macro: Ecto.Query.where/3
           iex:10: (file)
```

Using the [Ecto Query source](https://github.com/elixir-lang/ecto/blob/c519e85c9164278cff9c673fc490beb52fea1604/lib/ecto/query.ex#L114) as an example.

**Comment by TrevorS** [comment]
Have now tested with every version since `datetime_add` was introduced.  Works for select, does not work for where.
